### ISSUE TITLE
seg_LabFusion STEPS and STAPLE LNCC modes give incorrect results with > 256 input templates

### ISSUE THREAD

**Issue by imalone** [KCL-BMEIS/NiftySeg#10]
Internally seg_LabFusion uses char to index input templates, when the number of templates is greater than 256 this results in incorrect templates being chosen in STEPS and STAPLE LNCC modes, resulting in unpredictable output. This problem will increase with the number of templates as the proportion of incorrect high matching templates will increase. Additionally there is no indication to the user that this threshold has been exceeded and they will not be aware of the problem.
While evaluations within specific cohorts may find a smaller number of templates are acceptable, attempting to produce template libraries for a more diverse population by adding subjects will run into problems.
A relatively simple fix will be submitted as a pull request.

**Comment by mjorgecardoso** [comment]
Thanks for the pull request @imalone
