### ISSUE TITLE
Component labelling in seg_maths

### ISSUE THREAD

**Issue by soundray** [KCL-BMEIS/NiftySeg#6]
The -concomp6 and -concomp26 options do not work as expected. With the attached label file I get
 ```
$ seg_maths label -concomp26 comp-label
$ seg_stats comp-label -Nl t.csv 
Too many labels... the code only handles up to 1024 labels
[NiftySeg] Exit here. File: /build/source/seg-apps/seg_Stats.cpp:732
$ seg_stats comp-label -r
0 23718
```
Fixing the output for examination:
```
$ seg_maths comp-label -replace 23718 31 -replace 121 30 comp-label-fixed
$ seg_stats comp-label-fixed -Nl t.csv ; cat t.csv
108580,0,0,1,1,1,1,1,1,1,1,1,1,23692,4,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,1
```
The expected behaviour would be to assign consecutive numbers to the components, for example in order of size.

[label.nii.gz](https://github.com/KCL-BMEIS/NiftySeg/files/2996263/label.nii.gz)

**Comment by mjorgecardoso** [comment]
I believe it should be fixed in the latest commit. https://github.com/KCL-BMEIS/NiftySeg/commit/0cbdaa3a90587d0d055b1b481aaa6f3f60d24208
